function [fitresult, gof, f] = createFit(x, y, z)
%CREATEFIT(X,Y,Z)
%  Create a fit.
%
%  Data for 'f1' fit:
%      X Input : x
%      Y Input : y
%      Z Output: z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Dec-2017 19:03:59


%% Fit: 'Nearest neighbor interp.'.
[xData, yData, zData] = prepareSurfaceData( x, y, z );

% Set up fittype and options.
ft = 'nearestinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
f = figure( 'Name', 'Nearest neighbor interp.' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Nearest neighbor interp.', 'PoA vs. TDP, PP', 'Location', 'NorthWest' );
% Label axes
xlabel('TDP');
ylabel('PP');
zlabel('PoA');
grid on


